package com.gatekeeper.mobile.vpn.relay

import java.net.Socket
import java.util.concurrent.atomic.AtomicLong

enum class TcpState {
    SYN_RECEIVED,
    ESTABLISHED,
    FIN_WAIT,
    CLOSED
}

data class TcpSession(
    val srcIp: ByteArray,
    val srcPort: Int,
    val dstIp: ByteArray,
    val dstPort: Int,
    val realSocket: Socket,
    @Volatile var state: TcpState,
    // AtomicLong prevents race conditions between handleData() and relayFromServer()
    val clientSeq: AtomicLong, // Sequence number expected FROM the app
    val serverSeq: AtomicLong, // Sequence number generated BY us (to the app)
    var clientWindow: Int = 65535,
    @Volatile var sniInspected: Boolean = false, // Issue 5 fix: check SNI only once
    var lastActive: Long = System.currentTimeMillis()
)
